name: 'f1_data_warehouse'
version: '1.0.0'
config-version: 2

profile: 'f1_databricks'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  f1_data_warehouse:
    bronze:
      +schema: bronze
      +materialized: view
      +tags: ["bronze"]

    silver:
      +schema: silver
      +materialized: table
      +tags: ["silver"]

    marts:
      +schema: marts
      +materialized: table
      +tags: ["marts"]